auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: ANSIBLE_OWN_PUBLIC_IP
    kvstore:
      store: consul
      consul:
        host: http://ANSIBLE_S3_ENDPOINT:8500

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    ring:
      kvstore:
        store: consul
        consul:
          host: http://ANSIBLE_S3_ENDPOINT:8500
      heartbeat_timeout: 1m
      replication_factor: 1
    num_tokens: 128
    heartbeat_period: 5s
    join_after: 0s
    min_ready_duration: 10s
    final_sleep: 30s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_
        period: 24h

storage_config:
  aws:
    s3: s3://697d0993dd097f38d5b8:9f88738761b57c63f6a81bdfd471@ANSIBLE_S3_ENDPOINT:9000/loki
    s3forcepathstyle: true

  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    resync_interval: 5s
    shared_store: s3

limits_config:
  enforce_metric_name: false
  reject_old_samples: false
  reject_old_samples_max_age: 730h # 1 month
  max_streams_per_user: 10000 #10k
  per_stream_rate_limit: 10MB

chunk_store_config:
  chunk_cache_config:
    redis:
        endpoint: "ANSIBLE_S3_ENDPOINT:6379"
        timeout: 100ms
        expiration: 0s
  max_look_back_period: 0s
  write_dedupe_cache_config:
    redis:
      endpoint: "ANSIBLE_S3_ENDPOINT:6379"
      timeout: 100ms
      expiration: 0s

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 1
    inactive_write_throughput: 1
    provisioned_read_throughput: 5
    provisioned_write_throughput: 5
  index_tables_provisioning:
    inactive_read_throughput: 1
    inactive_write_throughput: 1
    provisioned_read_throughput: 5
    provisioned_write_throughput: 5
  retention_deletes_enabled: false
  retention_period: 0s
