server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"

positions:
    filename: /tmp/positions.yaml

clients:
    # 172.17.0.0/16 is local docker network
    - url: http://172.17.0.1:3101/loki/api/v1/push

scrape_configs:
  - job_name: scrape-generated-http
    static_configs:
      - targets:
          - localhost
        labels:
          job: generated-logs
          __path__: /var/log/generated-logs.txt
          host: ANSIBLE_HOST_NAME
    pipeline_stages:
      - json:
          expressions:
            http_method: 'method'
            http_status: "status"
      - labels:
          http_method:
          http_status:
