version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2022-03-11T23-57-45Z
    container_name: minio
    entrypoint: sh
    command: -c 'mkdir -p /export/loki && minio server /export'
    environment:
      - MINIO_ROOT_USER=697d0993dd097f38d5b8
      - MINIO_ROOT_PASSWORD=9f88738761b57c63f6a81bdfd471
    network_mode: host
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  consul:
    container_name: consul
    image: consul:1.9
    command: agent -log-level=info -dev -client 0.0.0.0
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    network_mode: host

  redis:
    image: bitnami/redis:6.0
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    network_mode: host
